# Generated by Django 4.1.1 on 2022-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=200)),
                ('doorCount', models.IntegerField()),
                ('accounting', models.BooleanField()),
            ],
        ),
    ]
